sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - ./node_modules/lighthouse/lighthouse-core/scripts/download-chrome.sh
  - start-stop-daemon --start --background --exec $(pwd)/chrome-linux/chrome
  - sleep 5
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
script:
  - npm run lighthouse
after_script:
  - npm run publish
